//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkumaNoMi
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Habilidades { get; set; }
        public bool Consumido { get; set; }
        public int TipoId { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
