//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remedio
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Dosagem { get; set; }
        public string Descricao { get; set; }
        public string Forma { get; set; }
        public string Validade { get; set; }
        public string Tipo { get; set; }
        public string Estoque { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
